### PR TITLE
Avoid mutation, add template literals

### PR DESCRIPTION
**Pull request by dangus21**
Added some template literals where there was string concatenation and scoped function argument to local variables to avoid reference mutation

### CODE REVIEW

**Review by luciferreeves — CHANGES_REQUESTED** [review]
Resolve conflicts - increase code coverage.

**Comment by dangus21** [comment]
the test runner isnt running all files for some reason... can you help me out with that?

**Comment by luciferreeves** [comment]
> the test runner isnt running all files for some reason... can you help me out with that?

If the PR is still in progress, mark it as a draft please. Also open PRs whenever you're completely done with your changes and do not want to add any extra files. I will check your test cases and let you know. 

Thanks

**Comment by luciferreeves** [comment]
> the test runner isnt running all files for some reason... can you help me out with that?

I tested your PR. All your tests pass. 

Cheers!

**Pull request closed without merging**
